name: Build documentation

on:
  push:
    branches:
      - gh-pages  # Or the branch you want to trigger the workflow on
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Use 16, 17, or 18 ( 16 best )

      - name: Install dependencies
        run: npm install 

      - name: Build
        run: npm run docs:build

      - name: Deploy to gh-pages
        run: |
          git config --global user.name "Supernova3339"
          git config --global user.email "supernova@superdev.one"
          git fetch origin gh-pages
          git branch -r | grep "origin/gh-pages"
          if [ $? -eq 0 ]; then
            git checkout gh-pages
          else
            git checkout -b gh-pages
          fi
          git add .
          git commit -m "Generate documentation"
          git push origin gh-pages
